# Generated by Django 4.0.6 on 2022-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('Id', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('DeviceType', models.CharField(max_length=20)),
                ('DeviceVersion', models.CharField(max_length=20)),
                ('DeviceLocation', models.CharField(max_length=50)),
                ('PrimaryGroup', models.CharField(max_length=50)),
                ('SecondaryGroup', models.CharField(max_length=50)),
                ('LastContact', models.TimeField(null=True)),
                ('Status', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
